### PR TITLE
[Feature] Add eslint and code refactor

### PR DESCRIPTION
**Pull request by fsschmitt**
## Summary
This PR tackles two main topics:
- Adds .eslintrc (based on [Airbnb Style Guide](https://github.com/airbnb/javascript));
- Refactors the code based on the eslint hints and issues.

**Note:** This PR should only be merged after the PR #3 
`[Feature] Add support for public holidays category`

### CODE REVIEW

**Comment by fsschmitt** [comment]
Prior merging this PR, please check PR#7 as it takes precedence to fix an issue.

**Comment by jkrnak** [comment]
Can you please rebase?

**Comment by fsschmitt** [comment]
I'll let you know when I have a finished version.

**Comment by fsschmitt** [comment]
Closing the PR until this issue is solved on my fork.

**Pull request closed without merging**
